export const countryCodes = [
    {
        "name":{
            "en":"Afghanistan",
            "ru":"Афганистан",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+93",
        "code":"AF",
        "flag":"🇦🇫"
    },
    {
        "name":{
            "en":"Albania",
            "ru":"Албания",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+355",
        "code":"AL",
        "flag":"🇦🇱"
    },
    {
        "name":{
            "en":"Algeria",
            "ru":"Алжир",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+213",
        "code":"DZ",
        "flag":"🇩🇿"
    },
    {
        "name":{
            "en":"American Samoa",
            "ru":"Американское Самоа",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1684",
        "code":"AS",
        "flag":"🇦🇸"
    },
    {
        "name":{
            "en":"Andorra",
            "ru":"Андорра",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+376",
        "code":"AD",
        "flag":"🇦🇩"
    },
    {
        "name":{
            "en":"Angola",
            "ru":"Ангола",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+244",
        "code":"AO",
        "flag":"🇦🇴"
    },
    {
        "name":{
            "en":"Anguilla",
            "ru":"Ангилья",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1264",
        "code":"AI",
        "flag":"🇦🇮"
    },
    {
        "name":{
            "en":"Antarctica",
            "ru":"Антарктида",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+672",
        "code":"AQ",
        "flag":"🇦🇶"
    },
    {
        "name":{
            "en":"Antigua and Barbuda",
            "ru":"Антигуа и Барбуда",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1268",
        "code":"AG",
        "flag":"🇦🇬"
    },
    {
        "name":{
            "en":"Argentina",
            "ru":"Аргентина",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+54",
        "code":"AR",
        "flag":"🇦🇷"
    },
    {
        "name":{
            "en":"Armenia",
            "ru":"Армения",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+374",
        "code":"AM",
        "flag":"🇦🇲"
    },
    {
        "name":{
            "en":"Aruba",
            "ru":"Аруба",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+297",
        "code":"AW",
        "flag":"🇦🇼"
    },
    {
        "name":{
            "en":"Australia",
            "ru":"Австралия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+61",
        "code":"AU",
        "flag":"🇦🇺"
    },
    {
        "name":{
            "en":"Austria",
            "ru":"Австрия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+43",
        "code":"AT",
        "flag":"🇦🇹"
    },
    {
        "name":{
            "en":"Azerbaijan",
            "ru":"Азербайджан",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+994",
        "code":"AZ",
        "flag":"🇦🇿"
    },
    {
        "name":{
            "en":"Bahamas",
            "ru":"Багамские Острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1242",
        "code":"BS",
        "flag":"🇧🇸"
    },
    {
        "name":{
            "en":"Bahrain",
            "ru":"Бахрейн",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+973",
        "code":"BH",
        "flag":"🇧🇭"
    },
    {
        "name":{
            "en":"Bangladesh",
            "ru":"Бангладеш",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+880",
        "code":"BD",
        "flag":"🇧🇩"
    },
    {
        "name":{
            "en":"Barbados",
            "ru":"Барбадос",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1246",
        "code":"BB",
        "flag":"🇧🇧"
    },
    {
        "name":{
            "en":"Belarus",
            "ru":"Белоруссия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+375",
        "code":"BY",
        "flag":"🇧🇾"
    },
    {
        "name":{
            "en":"Belgium",
            "ru":"Бельгия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+32",
        "code":"BE",
        "flag":"🇧🇪"
    },
    {
        "name":{
            "en":"Belize",
            "ru":"Белиз",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+501",
        "code":"BZ",
        "flag":"🇧🇿"
    },
    {
        "name":{
            "en":"Benin",
            "ru":"Бенин",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+229",
        "code":"BJ",
        "flag":"🇧🇯"
    },
    {
        "name":{
            "en":"Bermuda",
            "ru":"Бермуды",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1441",
        "code":"BM",
        "flag":"🇧🇲"
    },
    {
        "name":{
            "en":"Bhutan",
            "ru":"Бутан",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+975",
        "code":"BT",
        "flag":"🇧🇹"
    },
    {
        "name":{
            "en":"Bolivia",
            "ru":"Боливия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+591",
        "code":"BO",
        "flag":"🇧🇴"
    },
    {
        "name":{
            "en":"Bosnia and Herzegovina",
            "ru":"Босния и Герцеговина",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+387",
        "code":"BA",
        "flag":"🇧🇦"
    },
    {
        "name":{
            "en":"Botswana",
            "ru":"Ботсвана",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+267",
        "code":"BW",
        "flag":"🇧🇼"
    },
    {
        "name":{
            "en":"Brazil",
            "ru":"Бразилия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+55",
        "code":"BR",
        "flag":"🇧🇷"
    },
    {
        "name":{
            "en":"British Indian Ocean Territory",
            "ru":"Британская территория Индийского океана",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+246",
        "code":"IO",
        "flag":"🇮🇴"
    },
    {
        "name":{
            "en":"Brunei Darussalam",
            "ru":"Бруней-Даруссалам",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+673",
        "code":"BN",
        "flag":"🇧🇳"
    },
    {
        "name":{
            "en":"Bulgaria",
            "ru":"Болгария",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+359",
        "code":"BG",
        "flag":"🇧🇬"
    },
    {
        "name":{
            "en":"Burkina Faso",
            "ru":"Буркина-Фасо",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+226",
        "code":"BF",
        "flag":"🇧🇫"
    },
    {
        "name":{
            "en":"Burundi",
            "ru":"Бурунди",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+257",
        "code":"BI",
        "flag":"🇧🇮"
    },
    {
        "name":{
            "en":"Cambodia",
            "ru":"Камбоджа",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+855",
        "code":"KH",
        "flag":"🇰🇭"
    },
    {
        "name":{
            "en":"Cameroon",
            "ru":"Камерун",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+237",
        "code":"CM",
        "flag":"🇨🇲"
    },
    {
        "name":{
            "en":"Canada",
            "ru":"Канада",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1",
        "code":"CA",
        "flag":"🇨🇦"
    },
    {
        "name":{
            "en":"Cape Verde",
            "ru":"Кабо-Верде",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+238",
        "code":"CV",
        "flag":"🇨🇻"
    },
    {
        "name":{
            "en":"Cayman Islands",
            "ru":"Каймановы острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+345",
        "code":"KY",
        "flag":"🇰🇾"
    },
    {
        "name":{
            "en":"Central African Republic",
            "ru":"Центрально-Африканская Республика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+236",
        "code":"CF",
        "flag":"🇨🇫"
    },
    {
        "name":{
            "en":"Chad",
            "ru":"Чад",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+235",
        "code":"TD",
        "flag":"🇹🇩"
    },
    {
        "name":{
            "en":"Chile",
            "ru":"Чили",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+56",
        "code":"CL",
        "flag":"🇨🇱"
    },
    {
        "name":{
            "en":"China",
            "ru":"Китай",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+86",
        "code":"CN",
        "flag":"🇨🇳"
    },
    {
        "name":{
            "en":"Christmas Island",
            "ru":"Остров Рождества",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+61",
        "code":"CX",
        "flag":"🇨🇽"
    },
    {
        "name":{
            "en":"Cocos (Keeling) Islands",
            "ru":"Кокосовые (Килинг) острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+61",
        "code":"CC",
        "flag":"🇨🇨"
    },
    {
        "name":{
            "en":"Colombia",
            "ru":"Колумбия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+57",
        "code":"CO",
        "flag":"🇨🇴"
    },
    {
        "name":{
            "en":"Comoros",
            "ru":"Коморские острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+269",
        "code":"KM",
        "flag":"🇰🇲"
    },
    {
        "name":{
            "en":"Congo",
            "ru":"Конго",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+242",
        "code":"CG",
        "flag":"🇨🇬"
    },
    {
        "name":{
            "en":"Congo, The Democratic Republic of the",
            "ru":"Конго, Демократическая Республика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+243",
        "code":"CD",
        "flag":"🇨🇩"
    },
    {
        "name":{
            "en":"Cook Islands",
            "ru":"Острова Кука",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+682",
        "code":"CK",
        "flag":"🇨🇰"
    },
    {
        "name":{
            "en":"Costa Rica",
            "ru":"Коста-Рика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+506",
        "code":"CR",
        "flag":"🇨🇷"
    },
    {
        "name":{
            "en":"Cote d'Ivoire",
            "ru":"Кот-д'Ивуар",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+225",
        "code":"CI",
        "flag":"🇨🇮"
    },
    {
        "name":{
            "en":"Croatia",
            "ru":"Хорватия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+385",
        "code":"HR",
        "flag":"🇭🇷"
    },
    {
        "name":{
            "en":"Cuba",
            "ru":"Куба",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+53",
        "code":"CU",
        "flag":"🇨🇺"
    },
    {
        "name":{
            "en":"Cyprus",
            "ru":"Кипр",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+537",
        "code":"CY",
        "flag":"🇨🇾"
    },
    {
        "name":{
            "en":"Czech Republic",
            "ru":"Чехия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+420",
        "code":"CZ",
        "flag":"🇨🇿"
    },
    {
        "name":{
            "en":"Denmark",
            "ru":"Дания",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+45",
        "code":"DK",
        "flag":"🇩🇰"
    },
    {
        "name":{
            "en":"Djibouti",
            "ru":"Джибути",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+253",
        "code":"DJ",
        "flag":"🇩🇯"
    },
    {
        "name":{
            "en":"Dominica",
            "ru":"Доминика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1767",
        "code":"DM",
        "flag":"🇩🇲"
    },
    {
        "name":{
            "en":"Dominican Republic",
            "ru":"Доминиканская Респблика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1849",
        "code":"DO",
        "flag":"🇩🇴"
    },
    {
        "name":{
            "en":"Ecuador",
            "ru":"Эквадор",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+593",
        "code":"EC",
        "flag":"🇪🇨"
    },
    {
        "name":{
            "en":"Egypt",
            "ru":"Египет",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+20",
        "code":"EG",
        "flag":"🇪🇬"
    },
    {
        "name":{
            "en":"El Salvador",
            "ru":"Сальвадор",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+503",
        "code":"SV",
        "flag":"🇸🇻"
    },
    {
        "name":{
            "en":"Equatorial Guinea",
            "ru":"Экваториальная Гвинея",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+240",
        "code":"GQ",
        "flag":"🇬🇶"
    },
    {
        "name":{
            "en":"Eritrea",
            "ru":"Эритрея",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+291",
        "code":"ER",
        "flag":"🇪🇷"
    },
    {
        "name":{
            "en":"Estonia",
            "ru":"Эстония",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+372",
        "code":"EE",
        "flag":"🇪🇪"
    },
    {
        "name":{
            "en":"Ethiopia",
            "ru":"Эфиопия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+251",
        "code":"ET",
        "flag":"🇪🇹"
    },
    {
        "name":{
            "en":"Falkland Islands (Malvinas)",
            "ru":"Фолклендские острова (Malvinas)",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+500",
        "code":"FK",
        "flag":"🇫🇰"
    },
    {
        "name":{
            "en":"Faroe Islands",
            "ru":"Фарерские острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+298",
        "code":"FO",
        "flag":"🇫🇴"
    },
    {
        "name":{
            "en":"Fiji",
            "ru":"Фиджи",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+679",
        "code":"FJ",
        "flag":"🇫🇯"
    },
    {
        "name":{
            "en":"Finland",
            "ru":"Финляндия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+358",
        "code":"FI",
        "flag":"🇫🇮"
    },
    {
        "name":{
            "en":"France",
            "ru":"Франция",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+33",
        "code":"FR",
        "flag":"🇫🇷"
    },
    {
        "name":{
            "en":"French Guiana",
            "ru":"Французская Гвиана",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+594",
        "code":"GF",
        "flag":"🇬🇫"
    },
    {
        "name":{
            "en":"French Polynesia",
            "ru":"Французская Полинезия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+689",
        "code":"PF",
        "flag":"🇵🇫"
    },
    {
        "name":{
            "en":"Gabon",
            "ru":"Габон",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+241",
        "code":"GA",
        "flag":"🇬🇦"
    },
    {
        "name":{
            "en":"Gambia",
            "ru":"Гамбия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+220",
        "code":"GM",
        "flag":"🇬🇲"
    },
    {
        "name":{
            "en":"Georgia",
            "ru":"Грузия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+995",
        "code":"GE",
        "flag":"🇬🇪"
    },
    {
        "name":{
            "en":"Germany",
            "ru":"Германия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+49",
        "code":"DE",
        "flag":"🇩🇪"
    },
    {
        "name":{
            "en":"Ghana",
            "ru":"Гана",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+233",
        "code":"GH",
        "flag":"🇬🇭"
    },
    {
        "name":{
            "en":"Gibraltar",
            "ru":"Гибралтар",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+350",
        "code":"GI",
        "flag":"🇬🇮"
    },
    {
        "name":{
            "en":"Greece",
            "ru":"Греция",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+30",
        "code":"GR",
        "flag":"🇬🇷"
    },
    {
        "name":{
            "en":"Greenland",
            "ru":"Гренландия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+299",
        "code":"GL",
        "flag":"🇬🇱"
    },
    {
        "name":{
            "en":"Grenada",
            "ru":"Гренада",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1473",
        "code":"GD",
        "flag":"🇬🇩"
    },
    {
        "name":{
            "en":"Guadeloupe",
            "ru":"Гваделупа",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+590",
        "code":"GP",
        "flag":"🇬🇵"
    },
    {
        "name":{
            "en":"Guam",
            "ru":"Гуам",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1671",
        "code":"GU",
        "flag":"🇬🇺"
    },
    {
        "name":{
            "en":"Guatemala",
            "ru":"Гватемала",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+502",
        "code":"GT",
        "flag":"🇬🇹"
    },
    {
        "name":{
            "en":"Guernsey",
            "ru":"Гернси",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+44",
        "code":"GG",
        "flag":"🇬🇬"
    },
    {
        "name":{
            "en":"Guinea",
            "ru":"Гвинея",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+224",
        "code":"GN",
        "flag":"🇬🇳"
    },
    {
        "name":{
            "en":"Guinea-Bissau",
            "ru":"Гвинея-Бисау",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+245",
        "code":"GW",
        "flag":"🇬🇼"
    },
    {
        "name":{
            "en":"Guyana",
            "ru":"Гайана",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+595",
        "code":"GY",
        "flag":"🇬🇾"
    },
    {
        "name":{
            "en":"Haiti",
            "ru":"Гаити",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+509",
        "code":"HT",
        "flag":"🇭🇹"
    },
    {
        "name":{
            "en":"Holy See (Vatican City State)",
            "ru":"Святой Престол (Vatican City State)",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+379",
        "code":"VA",
        "flag":"🇻🇦"
    },
    {
        "name":{
            "en":"Honduras",
            "ru":"Гондурас",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+504",
        "code":"HN",
        "flag":"🇭🇳"
    },
    {
        "name":{
            "en":"Hong Kong",
            "ru":"Гонконг",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+852",
        "code":"HK",
        "flag":"🇭🇰"
    },
    {
        "name":{
            "en":"Hungary",
            "ru":"Венгрия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+36",
        "code":"HU",
        "flag":"🇭🇺"
    },
    {
        "name":{
            "en":"Iceland",
            "ru":"Исландия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+354",
        "code":"IS",
        "flag":"🇮🇸"
    },
    {
        "name":{
            "en":"India",
            "ru":"Индия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+91",
        "code":"IN",
        "flag":"🇮🇳"
    },
    {
        "name":{
            "en":"Indonesia",
            "ru":"Индонезия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+62",
        "code":"ID",
        "flag":"🇮🇩"
    },
    {
        "name":{
            "en":"Iran, Islamic Republic of",
            "ru":"Иран, Исламская Республика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+98",
        "code":"IR",
        "flag":"🇮🇷"
    },
    {
        "name":{
            "en":"Iraq",
            "ru":"Ирак",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+964",
        "code":"IQ",
        "flag":"🇮🇶"
    },
    {
        "name":{
            "en":"Ireland",
            "ru":"Ирландия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+353",
        "code":"IE",
        "flag":"🇮🇪"
    },
    {
        "name":{
            "en":"Isle of Man",
            "ru":"Остров Мэн",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+44",
        "code":"IM",
        "flag":"🇮🇲"
    },
    {
        "name":{
            "en":"Israel",
            "ru":"Израиль",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+972",
        "code":"IL",
        "flag":"🇮🇱"
    },
    {
        "name":{
            "en":"Italy",
            "ru":"Италия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+39",
        "code":"IT",
        "flag":"🇮🇹"
    },
    {
        "name":{
            "en":"Jamaica",
            "ru":"Ямайка",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1876",
        "code":"JM",
        "flag":"🇯🇲"
    },
    {
        "name":{
            "en":"Japan",
            "ru":"Япония",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+81",
        "code":"JP",
        "flag":"🇯🇵"
    },
    {
        "name":{
            "en":"Jersey",
            "ru":"Джерси",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+44",
        "code":"JE",
        "flag":"🇯🇪"
    },
    {
        "name":{
            "en":"Jordan",
            "ru":"Иордания",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+962",
        "code":"JO",
        "flag":"🇯🇴"
    },
    {
        "name":{
            "en":"Kazakhstan",
            "ru":"Казахстан",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+77",
        "code":"KZ",
        "flag":"🇰🇿"
    },
    {
        "name":{
            "en":"Kenya",
            "ru":"Кения",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+254",
        "code":"KE",
        "flag":"🇰🇪"
    },
    {
        "name":{
            "en":"Kiribati",
            "ru":"Кирибати",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+686",
        "code":"KI",
        "flag":"🇰🇮"
    },
    {
        "name":{
            "en":"Korea, Democratic People's Republic of",
            "ru":"Корея, Народно-Демократическая Республика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+850",
        "code":"KP",
        "flag":"🇰🇵"
    },
    {
        "name":{
            "en":"Korea, Republic of",
            "ru":"Республика Корея",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+82",
        "code":"KR",
        "flag":"🇰🇷"
    },
    {
        "name":{
            "en":"Kuwait",
            "ru":"Кувейт",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+965",
        "code":"KW",
        "flag":"🇰🇼"
    },
    {
        "name":{
            "en":"Kyrgyzstan",
            "ru":"Kyrgyzstan",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+996",
        "code":"KG",
        "flag":"🇰🇬"
    },
    {
        "name":{
            "en":"Lao People's Democratic Republic",
            "ru":"Лаосская Народно-Демократическая Республика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+856",
        "code":"LA",
        "flag":"🇱🇦"
    },
    {
        "name":{
            "en":"Latvia",
            "ru":"Латвия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+371",
        "code":"LV",
        "flag":"🇱🇻"
    },
    {
        "name":{
            "en":"Lebanon",
            "ru":"Ливан",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+961",
        "code":"LB",
        "flag":"🇱🇧"
    },
    {
        "name":{
            "en":"Lesotho",
            "ru":"Лесото",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+266",
        "code":"LS",
        "flag":"🇱🇸"
    },
    {
        "name":{
            "en":"Liberia",
            "ru":"Либерия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+231",
        "code":"LR",
        "flag":"🇱🇷"
    },
    {
        "name":{
            "en":"Libyan Arab Jamahiriya",
            "ru":"Ливийская Арабская Джамахирия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+218",
        "code":"LY",
        "flag":"🇱🇾"
    },
    {
        "name":{
            "en":"Liechtenstein",
            "ru":"Лихтенштейн",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+423",
        "code":"LI",
        "flag":"🇱🇮"
    },
    {
        "name":{
            "en":"Lithuania",
            "ru":"Литва",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+370",
        "code":"LT",
        "flag":"🇱🇹"
    },
    {
        "name":{
            "en":"Luxembourg",
            "ru":"Люксембург",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+352",
        "code":"LU",
        "flag":"🇱🇺"
    },
    {
        "name":{
            "en":"Macao",
            "ru":"Макао",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+853",
        "code":"MO",
        "flag":"🇲🇴"
    },
    {
        "name":{
            "en":"Macedonia, The Former Yugoslav Republic of",
            "ru":"Македония, Бывшая Югославская Республика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+389",
        "code":"MK",
        "flag":"🇲🇰"
    },
    {
        "name":{
            "en":"Madagascar",
            "ru":"Мадагаскар",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+261",
        "code":"MG",
        "flag":"🇲🇬"
    },
    {
        "name":{
            "en":"Malawi",
            "ru":"Малави",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+265",
        "code":"MW",
        "flag":"🇲🇼"
    },
    {
        "name":{
            "en":"Malaysia",
            "ru":"Малайзия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+60",
        "code":"MY",
        "flag":"🇲🇾"
    },
    {
        "name":{
            "en":"Maldives",
            "ru":"Мальдивы",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+960",
        "code":"MV",
        "flag":"🇲🇻"
    },
    {
        "name":{
            "en":"Mali",
            "ru":"Мали",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+223",
        "code":"ML",
        "flag":"🇲🇱"
    },
    {
        "name":{
            "en":"Malta",
            "ru":"Мальта",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+356",
        "code":"MT",
        "flag":"🇲🇹"
    },
    {
        "name":{
            "en":"Marshall Islands",
            "ru":"Маршалловы острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+692",
        "code":"MH",
        "flag":"🇲🇭"
    },
    {
        "name":{
            "en":"Martinique",
            "ru":"Мартиника",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+596",
        "code":"MQ",
        "flag":"🇲🇶"
    },
    {
        "name":{
            "en":"Mauritania",
            "ru":"Мавритания",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+222",
        "code":"MR",
        "flag":"🇲🇷"
    },
    {
        "name":{
            "en":"Mauritius",
            "ru":"Маврикий",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+230",
        "code":"MU",
        "flag":"🇲🇺"
    },
    {
        "name":{
            "en":"Mayotte",
            "ru":"Майотта",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+262",
        "code":"YT",
        "flag":"🇾🇹"
    },
    {
        "name":{
            "en":"Mexico",
            "ru":"Мексика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+52",
        "code":"MX",
        "flag":"🇲🇽"
    },
    {
        "name":{
            "en":"Micronesia, Federated States of",
            "ru":"Микронезия, Федеративные Штаты",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+691",
        "code":"FM",
        "flag":"🇫🇲"
    },
    {
        "name":{
            "en":"Moldova, Republic of",
            "ru":"Молдова, Республика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+373",
        "code":"MD",
        "flag":"🇲🇩"
    },
    {
        "name":{
            "en":"Monaco",
            "ru":"Монако",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+377",
        "code":"MC",
        "flag":"🇲🇨"
    },
    {
        "name":{
            "en":"Mongolia",
            "ru":"Монголия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+976",
        "code":"MN",
        "flag":"🇲🇳"
    },
    {
        "name":{
            "en":"Montenegro",
            "ru":"Черногория",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+382",
        "code":"ME",
        "flag":"🇲🇪"
    },
    {
        "name":{
            "en":"Montserrat",
            "ru":"Монтсеррат",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1664",
        "code":"MS",
        "flag":"🇲🇸"
    },
    {
        "name":{
            "en":"Morocco",
            "ru":"Марокко",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+212",
        "code":"MA",
        "flag":"🇲🇦"
    },
    {
        "name":{
            "en":"Mozambique",
            "ru":"Мозамбик",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+258",
        "code":"MZ",
        "flag":"🇲🇿"
    },
    {
        "name":{
            "en":"Myanmar",
            "ru":"Мьянма",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+95",
        "code":"MM",
        "flag":"🇲🇲"
    },
    {
        "name":{
            "en":"Namibia",
            "ru":"Намибия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+264",
        "code":"NA",
        "flag":"🇳🇦"
    },
    {
        "name":{
            "en":"Nauru",
            "ru":"Науру",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+674",
        "code":"NR",
        "flag":"🇳🇷"
    },
    {
        "name":{
            "en":"Nepal",
            "ru":"Непал",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+977",
        "code":"NP",
        "flag":"🇳🇵"
    },
    {
        "name":{
            "en":"Netherlands",
            "ru":"Нидерланды",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+31",
        "code":"NL",
        "flag":"🇳🇱"
    },
    {
        "name":{
            "en":"Netherlands Antilles",
            "ru":"Нидерландские Антильские острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+599",
        "code":"AN",
        "flag":"🇦🇳"
    },
    {
        "name":{
            "en":"New Caledonia",
            "ru":"Новая Каледония",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+687",
        "code":"NC",
        "flag":"🇳🇨"
    },
    {
        "name":{
            "en":"New Zealand",
            "ru":"Новая Зеландия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+64",
        "code":"NZ",
        "flag":"🇳🇿"
    },
    {
        "name":{
            "en":"Nicaragua",
            "ru":"Никарагуа",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+505",
        "code":"NI",
        "flag":"🇳🇮"
    },
    {
        "name":{
            "en":"Niger",
            "ru":"Нигер",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+227",
        "code":"NE",
        "flag":"🇳🇪"
    },
    {
        "name":{
            "en":"Nigeria",
            "ru":"Нигерия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+234",
        "code":"NG",
        "flag":"🇳🇬"
    },
    {
        "name":{
            "en":"Niue",
            "ru":"Ниуэ",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+683",
        "code":"NU",
        "flag":"🇳🇺"
    },
    {
        "name":{
            "en":"Norfolk Island",
            "ru":"Остров Норфолк",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+672",
        "code":"NF",
        "flag":"🇳🇫"
    },
    {
        "name":{
            "en":"Northern Mariana Islands",
            "ru":"Северные Марианские острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1670",
        "code":"MP",
        "flag":"🇲🇵"
    },
    {
        "name":{
            "en":"Norway",
            "ru":"Норвегия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+47",
        "code":"NO",
        "flag":"🇳🇴"
    },
    {
        "name":{
            "en":"Oman",
            "ru":"Оман",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+968",
        "code":"OM",
        "flag":"🇴🇲"
    },
    {
        "name":{
            "en":"Pakistan",
            "ru":"Пакистан",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+92",
        "code":"PK",
        "flag":"🇵🇰"
    },
    {
        "name":{
            "en":"Palau",
            "ru":"Палау",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+680",
        "code":"PW",
        "flag":"🇵🇼"
    },
    {
        "name":{
            "en":"Palestinian Territory, Occupied",
            "ru":"Палестинская Территория, Оккупированная",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+970",
        "code":"PS",
        "flag":"🇵🇸"
    },
    {
        "name":{
            "en":"Panama",
            "ru":"Панама",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+507",
        "code":"PA",
        "flag":"🇵🇦"
    },
    {
        "name":{
            "en":"Papua New Guinea",
            "ru":"Папуа - Новая Гвинея",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+675",
        "code":"PG",
        "flag":"🇵🇬"
    },
    {
        "name":{
            "en":"Paraguay",
            "ru":"Парагвай",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+595",
        "code":"PY",
        "flag":"🇵🇾"
    },
    {
        "name":{
            "en":"Peru",
            "ru":"Перу",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+51",
        "code":"PE",
        "flag":"🇵🇪"
    },
    {
        "name":{
            "en":"Philippines",
            "ru":"Филиппины",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+63",
        "code":"PH",
        "flag":"🇵🇭"
    },
    {
        "name":{
            "en":"Pitcairn",
            "ru":"Питкэрн",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+872",
        "code":"PN",
        "flag":"🇵🇳"
    },
    {
        "name":{
            "en":"Poland",
            "ru":"Польша",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+48",
        "code":"PL",
        "flag":"🇵🇱"
    },
    {
        "name":{
            "en":"Portugal",
            "ru":"Португалия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+351",
        "code":"PT",
        "flag":"🇵🇹"
    },
    {
        "name":{
            "en":"Puerto Rico",
            "ru":"Пуэрто-Рико",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1939",
        "code":"PR",
        "flag":"🇵🇷"
    },
    {
        "name":{
            "en":"Qatar",
            "ru":"Катар",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+974",
        "code":"QA",
        "flag":"🇶🇦"
    },
    {
        "name":{
            "en":"Romania",
            "ru":"Румыния",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+40",
        "code":"RO",
        "flag":"🇷🇴"
    },
    {
        "name":{
            "en":"Russia",
            "ru":"Россия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+7",
        "code":"RU",
        "flag":"🇷🇺"
    },
    {
        "name":{
            "en":"Rwanda",
            "ru":"Руанда",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+250",
        "code":"RW",
        "flag":"🇷🇼"
    },
    {
        "name":{
            "en":"Réunion",
            "ru":"Реюньон",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+262",
        "code":"RE",
        "flag":"🇷🇪"
    },
    {
        "name":{
            "en":"Saint Barthélemy",
            "ru":"Святой Варфоломей",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+590",
        "code":"BL",
        "flag":"🇧🇱"
    },
    {
        "name":{
            "en":"Saint Helena, Ascension and Tristan Da Cunha",
            "ru":"Святой Елены, Вознесения и Тристан-да-Кунья",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+290",
        "code":"SH",
        "flag":"🇸🇭"
    },
    {
        "name":{
            "en":"Saint Kitts and Nevis",
            "ru":"Сент-Китс и Невис",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1869",
        "code":"KN",
        "flag":"🇰🇳"
    },
    {
        "name":{
            "en":"Saint Lucia",
            "ru":"Санкт-Люсия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1758",
        "code":"LC",
        "flag":"🇱🇨"
    },
    {
        "name":{
            "en":"Saint Martin",
            "ru":"Сен-Мартен",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+590",
        "code":"MF",
        "flag":"🇲🇫"
    },
    {
        "name":{
            "en":"Saint Pierre and Miquelon",
            "ru":"Сен-Пьер и Микелон",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+508",
        "code":"PM",
        "flag":"🇵🇲"
    },
    {
        "name":{
            "en":"Saint Vincent and the Grenadines",
            "ru":"Святой Винсент и Гренадины",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1784",
        "code":"VC",
        "flag":"🇻🇨"
    },
    {
        "name":{
            "en":"Samoa",
            "ru":"Самоа",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+685",
        "code":"WS",
        "flag":"🇼🇸"
    },
    {
        "name":{
            "en":"San Marino",
            "ru":"Сан-Марино",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+378",
        "code":"SM",
        "flag":"🇸🇲"
    },
    {
        "name":{
            "en":"Sao Tome and Principe",
            "ru":"Сан-Томе и Принсипи",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+239",
        "code":"ST",
        "flag":"🇸🇹"
    },
    {
        "name":{
            "en":"Saudi Arabia",
            "ru":"Саудовская Аравия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+966",
        "code":"SA",
        "flag":"🇸🇦"
    },
    {
        "name":{
            "en":"Senegal",
            "ru":"Сенегал",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+221",
        "code":"SN",
        "flag":"🇸🇳"
    },
    {
        "name":{
            "en":"Serbia",
            "ru":"Сербия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+381",
        "code":"RS",
        "flag":"🇷🇸"
    },
    {
        "name":{
            "en":"Seychelles",
            "ru":"Сейшельские острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+248",
        "code":"SC",
        "flag":"🇸🇨"
    },
    {
        "name":{
            "en":"Sierra Leone",
            "ru":"Сьерра-Леоне",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+232",
        "code":"SL",
        "flag":"🇸🇱"
    },
    {
        "name":{
            "en":"Singapore",
            "ru":"Сингапур",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+65",
        "code":"SG",
        "flag":"🇸🇬"
    },
    {
        "name":{
            "en":"Slovakia",
            "ru":"Словакия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+421",
        "code":"SK",
        "flag":"🇸🇰"
    },
    {
        "name":{
            "en":"Slovenia",
            "ru":"Словения",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+386",
        "code":"SI",
        "flag":"🇸🇮"
    },
    {
        "name":{
            "en":"Solomon Islands",
            "ru":"Соломоновы острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+677",
        "code":"SB",
        "flag":"🇸🇧"
    },
    {
        "name":{
            "en":"Somalia",
            "ru":"Сомали",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+252",
        "code":"SO",
        "flag":"🇸🇴"
    },
    {
        "name":{
            "en":"South Africa",
            "ru":"Южная Африка",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+27",
        "code":"ZA",
        "flag":"🇿🇦"
    },
    {
        "name":{
            "en":"South Georgia and the South Sandwich Islands",
            "ru":"Южная Георгия и Южные Сандвичевы острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+500",
        "code":"GS",
        "flag":"🇬🇸"
    },
    {
        "name":{
            "en":"Spain",
            "ru":"Испания",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+34",
        "code":"ES",
        "flag":"🇪🇸"
    },
    {
        "name":{
            "en":"Sri Lanka",
            "ru":"Шри-Ланка",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+94",
        "code":"LK",
        "flag":"🇱🇰"
    },
    {
        "name":{
            "en":"Sudan",
            "ru":"Судан",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+249",
        "code":"SD",
        "flag":"🇸🇩"
    },
    {
        "name":{
            "en":"Suriname",
            "ru":"Суринам",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+597",
        "code":"SR",
        "flag":"🇸🇷"
    },
    {
        "name":{
            "en":"Svalbard and Jan Mayen",
            "ru":"Шпицберген и Ян Майен",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+47",
        "code":"SJ",
        "flag":"🇸🇯"
    },
    {
        "name":{
            "en":"Swaziland",
            "ru":"Свазиленд",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+268",
        "code":"SZ",
        "flag":"🇸🇿"
    },
    {
        "name":{
            "en":"Sweden",
            "ru":"Швеция",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+46",
        "code":"SE",
        "flag":"🇸🇪"
    },
    {
        "name":{
            "en":"Switzerland",
            "ru":"Швейцария",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+41",
        "code":"CH",
        "flag":"🇨🇭"
    },
    {
        "name":{
            "en":"Syrian Arab Republic",
            "ru":"Сирийская Арабская Республика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+963",
        "code":"SY",
        "flag":"🇸🇾"
    },
    {
        "name":{
            "en":"Taiwan, Province of China",
            "ru":"Тайвань, провинция Китая",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+886",
        "code":"TW",
        "flag":"🇹🇼"
    },
    {
        "name":{
            "en":"Tajikistan",
            "ru":"Таджикистан",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+992",
        "code":"TJ",
        "flag":"🇹🇯"
    },
    {
        "name":{
            "en":"Tanzania, United Republic of",
            "ru":"Танзания, Объединенная Республика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+255",
        "code":"TZ",
        "flag":"🇹🇿"
    },
    {
        "name":{
            "en":"Thailand",
            "ru":"Таиланд",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+66",
        "code":"TH",
        "flag":"🇹🇭"
    },
    {
        "name":{
            "en":"Timor-Leste",
            "ru":"Восточный Тимор",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+670",
        "code":"TL",
        "flag":"🇹🇱"
    },
    {
        "name":{
            "en":"Togo",
            "ru":"Того",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+228",
        "code":"TG",
        "flag":"🇹🇬"
    },
    {
        "name":{
            "en":"Tokelau",
            "ru":"Токелау",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+690",
        "code":"TK",
        "flag":"🇹🇰"
    },
    {
        "name":{
            "en":"Tonga",
            "ru":"Тонга",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+676",
        "code":"TO",
        "flag":"🇹🇴"
    },
    {
        "name":{
            "en":"Trinidad and Tobago",
            "ru":"Тринидад и Тобаго",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1868",
        "code":"TT",
        "flag":"🇹🇹"
    },
    {
        "name":{
            "en":"Tunisia",
            "ru":"Тунис",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+216",
        "code":"TN",
        "flag":"🇹🇳"
    },
    {
        "name":{
            "en":"Turkey",
            "ru":"Турция",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+90",
        "code":"TR",
        "flag":"🇹🇷"
    },
    {
        "name":{
            "en":"Turkmenistan",
            "ru":"Туркменистан",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+993",
        "code":"TM",
        "flag":"🇹🇲"
    },
    {
        "name":{
            "en":"Turks and Caicos Islands",
            "ru":"Острова Теркс и Кайкос",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1649",
        "code":"TC",
        "flag":"🇹🇨"
    },
    {
        "name":{
            "en":"Tuvalu",
            "ru":"Тувалу",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+688",
        "code":"TV",
        "flag":"🇹🇻"
    },
    {
        "name":{
            "en":"Uganda",
            "ru":"Уганда",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+256",
        "code":"UG",
        "flag":"🇺🇬"
    },
    {
        "name":{
            "en":"Ukraine",
            "ru":"Украина",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+380",
        "code":"UA",
        "flag":"🇺🇦"
    },
    {
        "name":{
            "en":"United Arab Emirates",
            "ru":"Объединенные Арабские Эмираты",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+971",
        "code":"AE",
        "flag":"🇦🇪"
    },
    {
        "name":{
            "en":"United Kingdom",
            "ru":"Объединенное Королевство",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+44",
        "code":"GB",
        "flag":"🇬🇧"
    },
    {
        "name":{
            "en":"United States",
            "ru":"Соединенные Штаты",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1",
        "code":"US",
        "flag":"🇺🇸"
    },
    {
        "name":{
            "en":"Uruguay",
            "ru":"Уругвай",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+598",
        "code":"UY",
        "flag":"🇺🇾"
    },
    {
        "name":{
            "en":"Uzbekistan",
            "ru":"Узбекистан",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+998",
        "code":"UZ",
        "flag":"🇺🇿"
    },
    {
        "name":{
            "en":"Vanuatu",
            "ru":"Вануату",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+678",
        "code":"VU",
        "flag":"🇻🇺"
    },
    {
        "name":{
            "en":"Venezuela, Bolivarian Republic of",
            "ru":"Венесуэла, Боливарианская Республика",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+58",
        "code":"VE",
        "flag":"🇻🇪"
    },
    {
        "name":{
            "en":"Viet Nam",
            "ru":"Вьетнам",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+84",
        "code":"VN",
        "flag":"🇻🇳"
    },
    {
        "name":{
            "en":"Virgin Islands, British",
            "ru":"Виргинские острова, Британские",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1284",
        "code":"VG",
        "flag":"🇻🇬"
    },
    {
        "name":{
            "en":"Virgin Islands, U.S.",
            "ru":"Американские Виргинские острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+1340",
        "code":"VI",
        "flag":"🇻🇮"
    },
    {
        "name":{
            "en":"Wallis and Futuna",
            "ru":"Уоллис и Футуна",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+681",
        "code":"WF",
        "flag":"🇼🇫"
    },
    {
        "name":{
            "en":"Yemen",
            "ru":"Йемен",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+967",
        "code":"YE",
        "flag":"🇾🇪"
    },
    {
        "name":{
            "en":"Zambia",
            "ru":"Замбия",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+260",
        "code":"ZM",
        "flag":"🇿🇲"
    },
    {
        "name":{
            "en":"Zimbabwe",
            "ru":"Зимбабве",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+263",
        "code":"ZW",
        "flag":"🇿🇼"
    },
    {
        "name":{
            "en":"Åland Islands",
            "ru":"Аландские острова",
            "pl":"",
            "ua":"",
            "cz":"",
            "by":""
        },
        "dial_code":"+358",
        "code":"AX",
        "flag":"🇦🇽"
    }
];
